let baseDePreguntas = [
    {
        pregunta: "¿Qué es python?",
        ayuda: "Pista: Python se utiliza para desarrollar aplicaciones de todo tipo, ejemplos: Instagram, Netflix, Spotify, entre otros.",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "Lenguaje de programación de alto nivel",
        distractores: ["Lenguaje de programación de nivel medio", "Lenguaje de programación de nivel bajo", "Juego de mesa"],
    },
    {
        pregunta: "¿Cuál de los siguientes lenguajes es orientado a objetos?",
        ayuda: "Pista: Este lenguaje es ampliamente utilizado en desarrollo empresarial y lleva el nombre de una isla de Indonesia.",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        respuesta: "Java",
        distractores: ["Pascal", "Python", "C"],
    },
    {
        pregunta: "¿Qué es un bucle 'for'?",
        ayuda: "Pista: Lleva dos puntos en su estructura y es una forma común de repetir un bloque de código.",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "Una estructura de control",
        distractores: ["Una variable", "Un tipo de dato", "Un operador matemático"],
    },
    {
        pregunta: "¿Qué es un array?",
        ayuda: "Pista: Es similar al bucle 'for' en la estructura y se utiliza para almacenar múltiples valores en una sola variable.",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "Una estructura de datos",
        distractores: ["Un tipo de error", "Un operador aritmético", "Un tipo de variable"],
    },
    {
        pregunta: "¿Cuál es el símbolo utilizado para asignar un valor a una variable en python?",
        ayuda: "Pista: Este símbolo se asemeja a dos rayas horizontales y se utiliza para asignar valores.",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "=",
        distractores: [":", "''", "=="],
    },
    {
        pregunta: "¿Qué es Git?",
        ayuda: "Pista: Es un sistema muy popular que ayuda a los desarrolladores a realizar un seguimiento de las versiones de su código",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "Un sistema de control de versiones",
        distractores: ["Un Id", "Un framework", "Un lenguaje de programación"],
    },
    {
        pregunta: "¿Cuál de los siguientes no es un lenguaje de programación?",
        ayuda: "Pista: Aunque se utiliza para estructurar el contenido de una página web, no es un lenguaje de programación.",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "HTML",
        distractores: ["C++", "C#", "Java"],
    },
    {
        pregunta: "¿Qué es un loop?",
        ayuda: "Pista: Es un término que a menudo se usa para referirse a un bucle que se repite hasta que se cumple una condición",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpgg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "Un bucle",
        distractores: ["Una función", "Una variable", "Un error"],
    },
    {
        pregunta: "¿Qué es una función en programación?",
        ayuda: "Pista: Es un conjunto de instrucciones agrupadas juntas con un nombre específico, que se puede llamar desde otras partes del código.",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "Un conjunto de instrucciones",
        distractores: ["Un tipo de dato", "Una variable", "Un operador lógico"],
    },
    {
        pregunta: "¿Qué es un bug?",
        ayuda: "Pista: Es un término utilizado para describir un problema en el código de un programa.",
        ayudaImg: "https://i.ibb.co/jkynpfj/52714-edit-555772569218145.jpg",
        imagen: "https://i.ibb.co/sv1qZn8/p7.jpg",
        respuesta: "Un error en el código",
        distractores: ["Una función de depuración", "Un dato", "Un operador lógico"],
    },
];
